### ISSUE TITLE
Error pulling this image

### ISSUE THREAD

**Issue by user-name-is-taken** [bborbe/git-sync#2]
When I try to pull this image I get this error:

```sh
$ docker pull bborbe/git-sync
Using default tag: latest
Error response from daemon: manifest for bborbe/git-sync:latest not found: manifest unknown: manifest unknown
```

But when I use `bborbe/git-sync:1.3.0` it works

**Comment by bborbe** [comment]
Best is to build the image yours self and push it to docker hub.
I rebuild git-sync and following version are available
bborbe/git-sync:latest
bborbe/git-sync:1.4.1
